services:
 - postgresql
language: ruby
before_script:
  - cp config/database.yml.travis config/database.yml
  - google-chrome --version
before_install:
  - google-chrome --no-sandbox --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
rvm:
  - 2.6.0
sudo: required
dist: trusty
addons:
  chrome: stable
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
script:
  - bundle exec rails db:create 
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec