services:
 - postgresql
language: ruby
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails runner "Webdrivers::Chromedriver.update"
rvm:
  - 2.6.0
addons:
  chrome: stable
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
    - PGPORT=5433
script:
  - bundle exec rails db:create 
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec