services:
 - postgresql
language: ruby
before_script:
  - cp config/database.yml.travis config/database.yml
  - ls -al /usr/bin/google-chrome
  - ps aux | grep chrome
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
rvm:
  - 2.6.0
sudo: required
dist: trusty
addons:
  chrome: stable
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
script:
  - bundle exec rails db:create 
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec