services:
 - postgresql
language: ruby
before_script:
  - cp config/database.yml.travis config/database.yml
  - ls -al /usr/bin/google-chrome
  - ps aux | grep chrome
  - wget -N http://chromedriver.storage.googleapis.com/2.46/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - sudo mv -f chromedriver /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
  - google-chrome --version
before_install:
  - google-chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
rvm:
  - 2.6.0
sudo: required
dist: trusty
addons:
  chrome: stable
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
script:
  - bundle exec rails db:create 
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec