development:
  aws_access_key_id:     'AKIAJIRW47SKIHK6SLVQ'                        # required unless using use_iam_profile
  aws_secret_access_key: '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' 
  bucket_name: '5x-pet-collage'  

production:
  aws_access_key_id:     'AKIAJIRW47SKIHK6SLVQ'                        # required unless using use_iam_profile
  aws_secret_access_key: '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' 
  bucket_name: '5x-pet-collage'  
